# Generated by Django 3.1.3 on 2020-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('contact_link', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('school_name', models.CharField(max_length=200)),
                ('degree_title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('details_description', models.TextField(blank=True, null=True)),
                ('school_site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('position_title', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_job', models.BooleanField(default=False)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('employer_site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('showcased', models.BooleanField(default=False)),
                ('project_title', models.CharField(max_length=200, unique=True)),
                ('project_showcase_link', models.URLField(blank=True, null=True)),
                ('project_sourcecode_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('show_years_exp', models.BooleanField(default=False)),
                ('skill_name', models.CharField(max_length=200, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('years_experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('show_years_exp', models.BooleanField(default=True)),
                ('tool_name', models.CharField(max_length=200, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('years_experience', models.IntegerField(default=0)),
            ],
        ),
    ]
