# Generated by Django 3.1.3 on 2020-11-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
