# Generated by Django 3.1.3 on 2020-11-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_resume', '0003_contact_contact_service_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobhistory',
            options={'verbose_name': 'Job History', 'verbose_name_plural': 'Job Histories'},
        ),
        migrations.RenameField(
            model_name='jobhistory',
            old_name='starting_date',
            new_name='start_date',
        ),
    ]
