# Generated by Django 3.1.3 on 2020-12-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_resume', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
