# Generated by Django 3.1.3 on 2020-12-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_resume', '0007_auto_20201213_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=True)),
                ('job_info', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_resume.jobhistory')),
            ],
            options={
                'verbose_name': 'Job History Info',
                'verbose_name_plural': 'Job Histories Info',
            },
        ),
    ]
